version: 2
updates:
- package-ecosystem: nuget
  directory: "/BackgroundServiceExample"
  schedule:
    interval: weekly
  open-pull-requests-limit: 2
- package-ecosystem: nuget
  directory: "/FactoryWorker"
  schedule:
    interval: weekly
  open-pull-requests-limit: 2
- package-ecosystem: nuget
  directory: "/Tests"
  schedule:
    interval: weekly
  open-pull-requests-limit: 2
  
